[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[profile.dev]
debug = false
opt-level = 0

[profile.release]
lto = "thin"
opt-level = "s"
strip = true
panic = "abort"
codegen-units = 1

[alias]
in = "binstall"

[build]
rustc-wrapper = "cachepot"
