#!/usr/bin/bash

hc() {
    herbstclient "$@"
}
normal="#1f1d2e"
focused="#6e6a86"

# Title
hc attr theme.title_height 0
hc attr theme.title_when always
hc attr theme.title_font 'IBM Plex Sans:pixelsize=12' 

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
#hc set frame_border_active_color '#222222cc'
#hc set frame_border_normal_color '#101010cc'
#hc set frame_bg_normal_color '#565656aa'
#hc set frame_bg_active_color '#345F0Caa'
#hc set frame_border_width 0 
#hc set show_frame_decorations 'focused_if_multiple'
#hc set frame_bg_transparent on
#hc set frame_transparent_width 0
#hc set frame_gap 0
#hc attr theme.title_depth 0  # space below the title's baseline
hc attr theme.tiling.outer_width 0
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0
#hc attr theme.floating.outer_color black
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'

hc attr theme.active.color $focused
hc attr theme.title_color '#ffffff'
hc attr theme.normal.color $normal
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.tab_color '#1F1F1Fdd'
hc attr theme.active.tab_color '#2B4F0Add'
hc attr theme.active.tab_outer_color '#6C8257dd'
hc attr theme.active.tab_title_color '#ababab'
hc attr theme.normal.title_color $normal
hc attr theme.active.inner_color $focused
hc attr theme.urgent.inner_color '#9ccfd8'
hc attr theme.normal.inner_color $normal
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 2
#hc attr theme.background_color '#1f1d2e'

hc set window_gap 10
hc set frame_padding 1
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0


# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
