#!/bin/bash


while true
do
  if pgrep -x gsd-xsettings > /dev/null     
  then
    break
  fi

  printf "."
  sleep 1
done

echo

export gnome_schema=org.gnome.desktop.interface

gsettings set $gnome_schema gtk-theme 'Materia-dark-compact'
gsettings set $gnome_schema icon-theme 'Papirus-Dark'
gsettings set $gnome_schema cursor-theme 'macOS-Monterey'
gsettings set $gnome_schema font-name 'Roboto'
