~/.fehbg &
/usr/lib/gsd-xsettings &
picom &

setxkbmap -variant intl us 

systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi

exec i3
