export PATH="$PATH:${HOME}/.local/bin"
export PATH="$PATH:${HOME}/.deno/bin"

if [ "${TTY}" = "/dev/tty1" ]
then
	echo "--> Starting Sway window manager" 
	export SDL_VIDEODRIVER=wayland
	export QT_QPA_PLATFORM=wayland
	export XDG_CURRENT_DESKTOP=sway
	export XDG_SESSION_DESKTOP=sway
	export DESKTOP_SESSION sway
	export MOZ_ENABLE_WAYLAND=1
	export MOZ_DBUS_REMOTE=1
	export _JAVA_AWT_WM_NONREPARENTING=1
	exec sway
fi

# eval $(opam env)

# Wasmer
export WASMER_DIR="${HOME}/.wasmer"
[ -s "$WASMER_DIR/wasmer.sh" ] && source "$WASMER_DIR/wasmer.sh"

# asdf
if [ -d "${HOME}/.asdf" ]; then
	source "$HOME/.asdf/asdf.sh"
	fpath+=${ASDF_DIR}/completions
fi
# asdf end

# pnpm
export PNPM_HOME="${HOME}/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

# rust
export PATH="${HOME}/.cargo/bin:$PATH"
# rust end

source ~/.zshrc-opts
source ~/.zshrc-theme
source ~/.zshrc-alias



