alias ls='lsd'
alias cat='batcat -p --theme=ansi'
alias dl-vid='yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"'

abbr -a gp      'git push'
abbr -a gcm     'git commit -m'
abbr -a clone   'git clone'
abbr -a rs      'cargo'
abbr -a rr      'cargo run'
abbr -a compose 'podman-compose' 
alias qtx11='env QT_QPA_PLATFORM=xcb'
